### ISSUE TITLE
Error starting with my configuration

### ISSUE THREAD

**Issue by BogusKladik** [nix-community/nix4vscode#51]
Tried to run the program using `cargo run -- myconfig.toml`
myconfig.toml:
```toml
vscode_version = "1.85.2"

[[extensions]]
publisher_name = "rust-lang"
extension_name = "rust-analyzer"

[[extensions]]
publisher_name = "jnoortheen"
extension_name = "nix-ide"

[[extensions]]
publisher_name = "arrterian"
extension_name = "nix-env-selector"

[[extensions]]
publisher_name = "tamasfe"
extension_name = "even-better-toml"

[[extensions]]
publisher_name = "Equinusocio"
extension_name = "vsc-material-theme"

[[extensions]]
publisher_name = "PKief"
extension_name = "material-icon-theme"

[[extensions]]
publisher_name = "nerg"
extension_name = "clips-lang"
```

I expected the configuration for nixos like last time. But I got an error:
```bash
> cargo run -- myconfig.toml
warning: unused import: `ReadableTable`
 --> src/utils/cacher.rs:2:12
  |
2 | use redb::{ReadableTable, TableDefinition};
  |            ^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `nix4vscode` (bin "nix4vscode") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/nix4vscode myconfig.toml`
thread 'main' panicked at src/utils/cacher.rs:48:53:
called `Result::unwrap()` on an `Err` value: UpgradeRequired(1)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

With RUST_BACKTRACE=1
```bash
> RUST_BACKTRACE=1 cargo run -- myconfig.toml
warning: unused import: `ReadableTable`
 --> src/utils/cacher.rs:2:12
  |
2 | use redb::{ReadableTable, TableDefinition};
  |            ^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `nix4vscode` (bin "nix4vscode") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/nix4vscode myconfig.toml`
thread 'main' panicked at src/utils/cacher.rs:48:53:
called `Result::unwrap()` on an `Err` value: UpgradeRequired(1)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/result.rs:1073:23
   4: nix4vscode::utils::cacher::Cacher::new
             at ./src/utils/cacher.rs:48:14
   5: <nix4vscode::utils::cacher::GLOBAL_CACHER as core::ops::deref::Deref>::deref::__static_ref_initialize
             at ./src/utils/cacher.rs:22:9
   6: core::ops::function::FnOnce::call_once
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/ops/function.rs:250:5
   7: lazy_static::lazy::Lazy<T>::get::{{closure}}
             at /home/boguskladik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lazy_static-1.4.0/src/inline_lazy.rs:31:29
   8: std::sync::once::Once::call_once::{{closure}}
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sync/once.rs:149:41
   9: std::sys_common::once::futex::Once::call
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/once/futex.rs:124:21
  10: std::sync::once::Once::call_once
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sync/once.rs:149:9
  11: lazy_static::lazy::Lazy<T>::get
             at /home/boguskladik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lazy_static-1.4.0/src/inline_lazy.rs:30:9
  12: <nix4vscode::utils::cacher::GLOBAL_CACHER as core::ops::deref::Deref>::deref::__stability
             at /home/boguskladik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lazy_static-1.4.0/src/lib.rs:142:21
  13: <nix4vscode::utils::cacher::GLOBAL_CACHER as core::ops::deref::Deref>::deref
             at /home/boguskladik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lazy_static-1.4.0/src/lib.rs:144:17
  14: nix4vscode::utils::get_sha256::{{closure}}
             at ./src/utils.rs:10:22
  15: nix4vscode::code::CodeNix::get_matched_versoin::{{closure}}
             at ./src/code.rs:168:62
  16: <futures_util::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
             at /home/boguskladik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/maybe_done.rs:95:38
  17: <futures_util::future::join_all::JoinAll<F> as core::future::future::Future>::poll
             at /home/boguskladik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/join_all.rs:143:24
  18: nix4vscode::code::CodeNix::get_extensions::{{closure}}
             at ./src/code.rs:80:27
  19: nix4vscode::main::{{closure}}
             at ./src/main.rs:44:54
  20: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/boguskladik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/park.rs:281:63
  21: tokio::runtime::coop::with_budget
             at /home/boguskladik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:107:5
  22: tokio::runtime::coop::budget
             at /home/boguskladik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:73:5
  23: tokio::runtime::park::CachedParkThread::block_on
             at /home/boguskladik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/park.rs:281:31
  24: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /home/boguskladik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/blocking.rs:66:9
  25: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /home/boguskladik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  26: tokio::runtime::context::runtime::enter_runtime
             at /home/boguskladik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/runtime.rs:65:16
  27: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/boguskladik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  28: tokio::runtime::runtime::Runtime::block_on
             at /home/boguskladik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/runtime.rs:351:45
  29: nix4vscode::main
             at ./src/main.rs:61:5
  30: core::ops::function::FnOnce::call_once
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by cathaysia** [comment]
this is a breaking changes from redb, you need remove `~/.cache/nix4vscode`

**Comment by BogusKladik** [comment]
> this is a breaking changes from redb, you need remove `~/.cache/nix4vscode`

Wow, it worked. Thank you!
